# http://www.arguslab.org/software/mulval.html
# Vars
- name: "Set parameters"
  set_fact:
          mulval_path: "{{ mulval_home }}/bin:{{ mulval_home }}/utils:{{xsb_home}}/bin"


- name: "Set MULVALROOT"
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^MULVALROOT'
    line: 'MULVALROOT={{ mulval_home }}'
    insertbefore: true
  become: yes

- name: "add {{mulval_path}} to path"
  lineinfile:
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{mulval_path}}).*?)(["]*)$'
    line="PATH=\1\2:{{mulval_path}}\3"
  become: yes

- name: register ancient java ppa
  become: yes
  apt_repository: repo=ppa:openjdk-r/ppa
  environment: 
    APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: True

- name: install openjdk-8
  become: yes
  apt: 
    pkg:
      - openjdk-8-jdk
  update_cache: yes

- name: "Install dependencies"
  become: yes
  apt:
    pkg:
      - git
      - python-pip
      - autoconf
      - build-essential
      - graphviz
      - mysql-server
        #- default-jdk
        #- openjdk-7-jdk
      - flex
      - bison
      - texlive-font-utils

    state: present
    #when: ansible_python_version == "2.7.6"

  # https://github.com/flavioc/XSB/blob/master/INSTALL
- name: "ensure xsb install path exists"
  file:
    path: "{{xsb_install_dir}}"
    state: directory
    owner: "{{ansible_user_id}}"
  tags: xsb
  become: yes

- name: "unpack xsb"
  unarchive:
    src: http://xsb.sourceforge.net/downloads/XSB.tar.gz
    dest: "{{xsb_install_dir}}"
    remote_src: yes
    creates: "{{xsb_home}}/InstallXSB.jar"
    owner: "{{ansible_user_id}}"
  tags: xsb

- name: "build xsb"
  shell: ./configure && ./makexsb
  args:
      chdir: "{{xsb_home}}/build"
      creates: "{{xsb_home}}/bin/xsb"


 # http://people.cs.ksu.edu/~xou/argus/software/mulval/readme.html
- name: "ensure mulval path exists"
  become: yes
  file:
    path: "{{mulval_home}}"
    state: directory
    owner: "{{ansible_user_id}}"
  tags: mulval

- name: "unpack mulval"
  unarchive:
    src: http://www.arguslab.org/software/mulval_1_1.tar.gz
    dest: "{{mulval_install_dir}}"
    remote_src: yes
    creates: "{{ mulval_home }}/Makefile"
    owner: "{{ansible_user_id}}"
  tags: mulval

  # Fix NVD name change
  #   String fname="nvd_xml_files/nvdcve-"+Integer.toString(ct)+".xml
  # Yaml requires escaping backslashes in double quotes but not in single quotes
  #- name: fix nvd file name change for db sync
  #replace:
  #  path: "{{ mulval_home }}/src/adapter/InitializeDB.java"
  #  regexp: 'nvdcve-[^2]'
  #  replace: 'nvdcve-2.0-"'

- name: add db connect parms to config.txt
  template:
    src: templates/config.txt.j2
    dest: "{{ mulval_home }}/utils/config.txt"

- name: fix nvd_sync.sh file name and type changes
  replace:
    path: "{{ mulval_home }}/utils/nvd_sync.sh"
    regexp: '^(.*)http://nvd.nist.gov/download/nvdcve-\$i.xml(.*)$'
    #replace: '\1http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-$i.xml.zip\2'
    replace: '\1https://nvd.nist.gov/download/nvdcve-$i.xml.gz\2'
    backup: True

- name: update nvd_sync.sh to unzip archives
  lineinfile: 
    path: "{{ mulval_home }}/utils/nvd_sync.sh"
    insertafter: '^(\s*)\w.*https://nvd.nist.gov/download/nvdcve-\$i.xml.gz$' 
    line: '      gunzip nvdcve-$i.xml.gz'
    regexp: '.*gunzip nvdcve-\$i.xml.gz.*'


- name: Replace InitializeDB.java to add score field
  copy:
    src: InitializeDB.java
    dest: "{{ mulval_home }}/src/adapter/InitializeDB.java"
    owner: vagrant
    group: vagrant
    mode: 0755

- name: check if mulval is built  
  stat: 
    path: "{{ mulval_home }}/bin/attack_graph" 
  register: mulval_build

- name: "build mulval"
  make:
    chdir: "{{ mulval_home }}"
    target: all
  environment:
    MULVALROOT: "{{ mulval_home }}"
  when: mulval_build.stat.exists == False

  #### mysql checks and setup
  # this is slow so only proceed if necessary

- name: check if nvd db is available
  shell: "mysql --defaults-extra-file=<(printf '[client]\nuser = %s\npassword = %s' nvd nvd)  -e 'show databases;' | grep -c {{nvd_db_schema}}"
  args:
    executable: /bin/bash
  register: dbstatus
  no_log: False
  failed_when: dbstatus.rc > 1 # 1 means no matches... not an error
  tags: [db]
  when: mulval_sync_nvd == True

- name: check if nvd table is available
  become: True
  shell: "mysql  --defaults-extra-file=<(printf '[client]\nuser = %s\npassword = %s' nvd nvd) -e 'use {{nvd_db_schema}}; show tables;' | grep -c {{nvd_db_schema}}"
  args:
    executable: /bin/bash
  register: tablestatus
  no_log: False
  failed_when: tablestatus.rc > 1 # 1 means no matches... not an error
  tags: [db]
  when: mulval_sync_nvd == True and dbstatus.rc == 0

- name: show dbstatus
  debug: 
    var: dbstatus
  tags: [db]
  when: mulval_sync_nvd == True

- name: check if nvd is populated
  become: True
  shell: "mysql --defaults-extra-file=<(printf '[client]\nuser = %s\npassword = %s' nvd nvd) -e 'select count(*) from nvd.nvd' | grep '[0-9]'"
  args:
    executable: /bin/bash
  register: dbfull
  no_log: False
  failed_when: dbfull.rc > 1 # 1 means no matches... not an error
  when: mulval_sync_nvd == True and tablestatus.rc == 0
  tags: [db]
  
- name: show dbfull
  debug:
    var: dbfull
  when: mulval_sync_nvd == True
  tags: [db]

 #- name: load nvd data
- name: sync mulval nvd db (set mulval_sync_nvd to False to disable)
  shell: "/bin/bash {{mulval_home}}/utils/nvd_sync.sh"
  args:
    chdir: "{{mulval_home}}/utils"
  when: mulval_sync_nvd == True and (dbstatus.rc != 0 or tablestatus.rc !=0)
  tags: [db]
